[project]
name = "stanford-cs336"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "ipykernel>=7.1.0",
    "regex>=2025.10.23",
    "scalene>=1.5.55",
    "tqdm>=4.67.1",
]
